//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigosha {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyAppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyAppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Knigosha.MyAppResources", typeof(MyAppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:1,&quot;title&quot;:&quot;Москва&quot;},{&quot;id&quot;:2,&quot;title&quot;:&quot;Санкт-Петербург&quot;},{&quot;id&quot;:10,&quot;title&quot;:&quot;Волгоград&quot;},{&quot;id&quot;:37,&quot;title&quot;:&quot;Владивосток&quot;},{&quot;id&quot;:42,&quot;title&quot;:&quot;Воронеж&quot;},{&quot;id&quot;:49,&quot;title&quot;:&quot;Екатеринбург&quot;},{&quot;id&quot;:60,&quot;title&quot;:&quot;Казань&quot;},{&quot;id&quot;:61,&quot;title&quot;:&quot;Калининград&quot;},{&quot;id&quot;:72,&quot;title&quot;:&quot;Краснодар&quot;},{&quot;id&quot;:73,&quot;title&quot;:&quot;Красноярск&quot;},{&quot;id&quot;:95,&quot;title&quot;:&quot;Нижний Новгород&quot;},{&quot;id&quot;:99,&quot;title&quot;:&quot;Новосибирск&quot;},{&quot;id&quot;:104,&quot;title&quot;:&quot;Омск&quot;},{&quot;id&quot;:110,&quot;title&quot;:&quot;Пермь&quot;},{&quot;id&quot;:119,&quot;title&quot;:&quot;Ростов-на-Дону&quot;},{&quot;id&quot;:123,&quot;title&quot;:&quot;Самара&quot;},{&quot;id&quot;:151,&quot;title&quot;:&quot;Уфа [re....
        /// </summary>
        public static string CitiesJson {
            get {
                return ResourceManager.GetString("CitiesJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 19,
        ///    &quot;title&quot;: &quot;Австралия&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: 20,
        ///    &quot;title&quot;: &quot;Австрия&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: 5,
        ///    &quot;title&quot;: &quot;Азербайджан&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: 21,
        ///    &quot;title&quot;: &quot;Албания&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: 22,
        ///    &quot;title&quot;: &quot;Алжир&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: 23,
        ///    &quot;title&quot;: &quot;Американское Самоа&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: 24,
        ///    &quot;title&quot;: &quot;Ангилья&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: 25,
        ///    &quot;title&quot;: &quot;Ангола&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: 26,
        ///    &quot;title&quot;: &quot;Андорра&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: 27,
        ///    &quot;title&quot;: &quot;Антигуа и Барбуда&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: 28,
        ///    &quot;titl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CountriesJson {
            get {
                return ResourceManager.GetString("CountriesJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 1777157,
        ///    &quot;title&quot;: &quot;Образовательный центр № 1&quot;,
        ///    &quot;cityId&quot;: 158
        ///  },
        ///  {
        ///    &quot;id&quot;: 110372,
        ///    &quot;title&quot;: &quot;Школа № 1&quot;,
        ///    &quot;cityId&quot;: 158
        ///  },
        ///  {
        ///    &quot;id&quot;: 122563,
        ///    &quot;title&quot;: &quot;Еврейская школа  № 1&quot;,
        ///    &quot;cityId&quot;: 158
        ///  },
        ///  {
        ///    &quot;id&quot;: 215875,
        ///    &quot;title&quot;: &quot;Гимназия № 1&quot;,
        ///    &quot;cityId&quot;: 158
        ///  },
        ///  {
        ///    &quot;id&quot;: 267160,
        ///    &quot;title&quot;: &quot;Школа-интернат № 1&quot;,
        ///    &quot;cityId&quot;: 158
        ///  },
        ///  {
        ///    &quot;id&quot;: 187137,
        ///    &quot;title&quot;: &quot;Музыкальная школа № 1&quot;,
        ///    &quot;cityId&quot;: 158
        ///  },
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsChelyabinskJson {
            get {
                return ResourceManager.GetString("SchoolsChelyabinskJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 83547,
        ///    &quot;title&quot;: &quot;Учебно-производственный комбинат (УПК) №1&quot;,
        ///    &quot;cityId&quot;: 49
        ///  },
        ///  {
        ///    &quot;id&quot;: 49644,
        ///    &quot;title&quot;: &quot;Школа №1&quot;,
        ///    &quot;cityId&quot;: 49
        ///  },
        ///  {
        ///    &quot;id&quot;: 163952,
        ///    &quot;title&quot;: &quot;Учебно-тренировочный центр «Омега-1»&quot;,
        ///    &quot;cityId&quot;: 49
        ///  },
        ///  {
        ///    &quot;id&quot;: 33261,
        ///    &quot;title&quot;: &quot;Учебно-тренировочный центр №1&quot;,
        ///    &quot;cityId&quot;: 49
        ///  },
        ///  {
        ///    &quot;id&quot;: 1749802,
        ///    &quot;title&quot;: &quot;Учебный центр №1 Свердловской железной дороги-филиала ОАО «РЖД»&quot;,
        ///    &quot;cityId&quot;: 49
        ///  },
        ///  {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsEkatirenburgJson {
            get {
                return ResourceManager.GetString("SchoolsEkatirenburgJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 174115,
        ///    &quot;title&quot;: &quot;Школа №1&quot;,
        ///    &quot;cityId&quot;: 153
        ///  },
        ///  {
        ///    &quot;id&quot;: 136114,
        ///    &quot;title&quot;: &quot;Кадетская школа №1 им. Ф. Ф. Ушакова&quot;,
        ///    &quot;cityId&quot;: 153
        ///  },
        ///  {
        ///    &quot;id&quot;: 27398,
        ///    &quot;title&quot;: &quot;Гимназия №1&quot;,
        ///    &quot;cityId&quot;: 153
        ///  },
        ///  {
        ///    &quot;id&quot;: 60463,
        ///    &quot;title&quot;: &quot;Технический лицей №1&quot;,
        ///    &quot;cityId&quot;: 153
        ///  },
        ///  {
        ///    &quot;id&quot;: 127308,
        ///    &quot;title&quot;: &quot;Школа-интернат №1 (ДВЖД)&quot;,
        ///    &quot;cityId&quot;: 153
        ///  },
        ///  {
        ///    &quot;id&quot;: 160055,
        ///    &quot;title&quot;: &quot;Музыкальная школа №1&quot;,
        ///    &quot;cityId&quot;: 1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsHabarovskJson {
            get {
                return ResourceManager.GetString("SchoolsHabarovskJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 64432,
        ///    &quot;title&quot;: &quot;Школа № 1&quot;,
        ///    &quot;cityId&quot;: 61
        ///  },
        ///  {
        ///    &quot;id&quot;: 3058,
        ///    &quot;title&quot;: &quot;Гимназия № 1&quot;,
        ///    &quot;cityId&quot;: 61
        ///  },
        ///  {
        ///    &quot;id&quot;: 69388,
        ///    &quot;title&quot;: &quot;Музыкальная школа при гимн. 1&quot;,
        ///    &quot;cityId&quot;: 61
        ///  },
        ///  {
        ///    &quot;id&quot;: 136610,
        ///    &quot;title&quot;: &quot;Спортивная школа олимпийского резерва № 1 по спортивной гимнастике&quot;,
        ///    &quot;cityId&quot;: 61
        ///  },
        ///  {
        ///    &quot;id&quot;: 170673,
        ///    &quot;title&quot;: &quot;Детско-юношеская спортивная школа №  1&quot;,
        ///    &quot;cityId&quot;: 61
        ///  },
        ///  {
        ///    &quot;id&quot;: 320118,
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsKaliningradJson {
            get {
                return ResourceManager.GetString("SchoolsKaliningradJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 216032,
        ///    &quot;title&quot;: &quot;Детско-юношеская спортивная школа №1&quot;,
        ///    &quot;cityId&quot;: 60
        ///  },
        ///  {
        ///    &quot;id&quot;: 47755,
        ///    &quot;title&quot;: &quot;Лицей №1 при КГУ&quot;,
        ///    &quot;cityId&quot;: 60
        ///  },
        ///  {
        ///    &quot;id&quot;: 222868,
        ///    &quot;title&quot;: &quot;Межшкольный учебный комбинат №1 Московского района&quot;,
        ///    &quot;cityId&quot;: 60
        ///  },
        ///  {
        ///    &quot;id&quot;: 38148,
        ///    &quot;title&quot;: &quot;Художественная школа №1&quot;,
        ///    &quot;cityId&quot;: 60
        ///  },
        ///  {
        ///    &quot;id&quot;: 37198,
        ///    &quot;title&quot;: &quot;Гимназия №1&quot;,
        ///    &quot;cityId&quot;: 60
        ///  },
        ///  {
        ///    &quot;id&quot;: 210284,
        ///    &quot;title&quot;: &quot;Училище  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsKazanJson {
            get {
                return ResourceManager.GetString("SchoolsKazanJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 2214,
        ///    &quot;title&quot;: &quot;Школа № 1&quot;,
        ///    &quot;cityId&quot;: 72
        ///  },
        ///  {
        ///    &quot;id&quot;: 104876,
        ///    &quot;title&quot;: &quot;Частная школа № 1&quot;,
        ///    &quot;cityId&quot;: 72
        ///  },
        ///  {
        ///    &quot;id&quot;: 132669,
        ///    &quot;title&quot;: &quot;Гимназия № 1&quot;,
        ///    &quot;cityId&quot;: 72
        ///  },
        ///  {
        ///    &quot;id&quot;: 111308,
        ///    &quot;title&quot;: &quot;Лицей № 1&quot;,
        ///    &quot;cityId&quot;: 72
        ///  },
        ///  {
        ///    &quot;id&quot;: 71083,
        ///    &quot;title&quot;: &quot;Музыкальная школа № 1&quot;,
        ///    &quot;cityId&quot;: 72
        ///  },
        ///  {
        ///    &quot;id&quot;: 266285,
        ///    &quot;title&quot;: &quot;Детско-юношеская спортивная школа № 1&quot;,
        ///    &quot;cityId&quot;: 72
        ///  },
        ///  {
        ///    &quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsKrasnodarJson {
            get {
                return ResourceManager.GetString("SchoolsKrasnodarJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 244047,
        ///    &quot;title&quot;: &quot;Межшкольный учебный комбинат № 1&quot;,
        ///    &quot;cityId&quot;: 73
        ///  },
        ///  {
        ///    &quot;id&quot;: 239718,
        ///    &quot;title&quot;: &quot;Школа № 1 им. В. И. Сурикова&quot;,
        ///    &quot;cityId&quot;: 73
        ///  },
        ///  {
        ///    &quot;id&quot;: 90808,
        ///    &quot;title&quot;: &quot;Центр образования 1&quot;,
        ///    &quot;cityId&quot;: 73
        ///  },
        ///  {
        ///    &quot;id&quot;: 53833,
        ///    &quot;title&quot;: &quot;Гимназия № 1 «Универс»&quot;,
        ///    &quot;cityId&quot;: 73
        ///  },
        ///  {
        ///    &quot;id&quot;: 69385,
        ///    &quot;title&quot;: &quot;Лицей № 1&quot;,
        ///    &quot;cityId&quot;: 73
        ///  },
        ///  {
        ///    &quot;id&quot;: 177795,
        ///    &quot;title&quot;: &quot;Школа-интернат № 1 им. В. П. Синяк [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsKrasnoyarskJson {
            get {
                return ResourceManager.GetString("SchoolsKrasnoyarskJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 29625,
        ///    &quot;title&quot;: &quot;Школа №1&quot;,
        ///    &quot;cityId&quot;: 1
        ///  },
        ///  {
        ///    &quot;id&quot;: 416430,
        ///    &quot;title&quot;: &quot;Церковно-приходская школа №1 им. Победоносцева&quot;,
        ///    &quot;cityId&quot;: 1
        ///  },
        ///  {
        ///    &quot;id&quot;: 3717,
        ///    &quot;title&quot;: &quot;Центр образования «Бескудниковский» — Корпус №1 (бывш. шк. №849)&quot;,
        ///    &quot;cityId&quot;: 1
        ///  },
        ///  {
        ///    &quot;id&quot;: 5046,
        ///    &quot;title&quot;: &quot;Школа «Образование плюс - 1»&quot;,
        ///    &quot;cityId&quot;: 1
        ///  },
        ///  {
        ///    &quot;id&quot;: 1763006,
        ///    &quot;title&quot;: &quot;Центр искусств №1 «Артис»&quot;,
        ///    &quot;cityId&quot;: 1
        ///  },
        ///  {
        ///    &quot;id&quot;: 20 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsMoskowJson {
            get {
                return ResourceManager.GetString("SchoolsMoskowJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 1751878,
        ///    &quot;title&quot;: &quot;Школа-интернат №1&quot;,
        ///    &quot;cityId&quot;: 95
        ///  },
        ///  {
        ///    &quot;id&quot;: 198562,
        ///    &quot;title&quot;: &quot;Медицинское училище №1 (НМУ)&quot;,
        ///    &quot;cityId&quot;: 95
        ///  },
        ///  {
        ///    &quot;id&quot;: 102927,
        ///    &quot;title&quot;: &quot;Школа №1&quot;,
        ///    &quot;cityId&quot;: 95
        ///  },
        ///  {
        ///    &quot;id&quot;: 2300,
        ///    &quot;title&quot;: &quot;Гимназия №1&quot;,
        ///    &quot;cityId&quot;: 95
        ///  },
        ///  {
        ///    &quot;id&quot;: 139060,
        ///    &quot;title&quot;: &quot;Лицей №1&quot;,
        ///    &quot;cityId&quot;: 95
        ///  },
        ///  {
        ///    &quot;id&quot;: 98811,
        ///    &quot;title&quot;: &quot;Музыкальная школа №1&quot;,
        ///    &quot;cityId&quot;: 95
        ///  },
        ///  {
        ///    &quot;id&quot;: 13237,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsNovgorodJson {
            get {
                return ResourceManager.GetString("SchoolsNovgorodJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 133484,
        ///    &quot;title&quot;: &quot;Прогимназия №1&quot;,
        ///    &quot;cityId&quot;: 99
        ///  },
        ///  {
        ///    &quot;id&quot;: 1780312,
        ///    &quot;title&quot;: &quot;Новосибирский центр профессионального обучения №1&quot;,
        ///    &quot;cityId&quot;: 99
        ///  },
        ///  {
        ///    &quot;id&quot;: 58888,
        ///    &quot;title&quot;: &quot;Школа №1&quot;,
        ///    &quot;cityId&quot;: 99
        ///  },
        ///  {
        ///    &quot;id&quot;: 290,
        ///    &quot;title&quot;: &quot;Гимназия №1&quot;,
        ///    &quot;cityId&quot;: 99
        ///  },
        ///  {
        ///    &quot;id&quot;: 165325,
        ///    &quot;title&quot;: &quot;Школа-интернат №1&quot;,
        ///    &quot;cityId&quot;: 99
        ///  },
        ///  {
        ///    &quot;id&quot;: 1698663,
        ///    &quot;title&quot;: &quot;Вечерняя школа №1&quot;,
        ///    &quot;cityId&quot;: 99
        ///  },        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsNovosibirskJson {
            get {
                return ResourceManager.GetString("SchoolsNovosibirskJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 166779,
        ///    &quot;title&quot;: &quot;Школа № 1&quot;,
        ///    &quot;cityId&quot;: 104
        ///  },
        ///  {
        ///    &quot;id&quot;: 203881,
        ///    &quot;title&quot;: &quot;Гимназия № 1&quot;,
        ///    &quot;cityId&quot;: 104
        ///  },
        ///  {
        ///    &quot;id&quot;: 53358,
        ///    &quot;title&quot;: &quot;Лицей при педагогическом колледже № 1&quot;,
        ///    &quot;cityId&quot;: 104
        ///  },
        ///  {
        ///    &quot;id&quot;: 228215,
        ///    &quot;title&quot;: &quot;Лицей № 1&quot;,
        ///    &quot;cityId&quot;: 104
        ///  },
        ///  {
        ///    &quot;id&quot;: 159456,
        ///    &quot;title&quot;: &quot;Школа-интернат № 1&quot;,
        ///    &quot;cityId&quot;: 104
        ///  },
        ///  {
        ///    &quot;id&quot;: 115715,
        ///    &quot;title&quot;: &quot;Музыкальная школа № 1&quot;,
        ///    &quot;cityId&quot;: 104
        ///  },
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsOmskJson {
            get {
                return ResourceManager.GetString("SchoolsOmskJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 148456,
        ///    &quot;title&quot;: &quot;Школа искусств №1&quot;,
        ///    &quot;cityId&quot;: 110
        ///  },
        ///  {
        ///    &quot;id&quot;: 178708,
        ///    &quot;title&quot;: &quot;Педагогический колледж №1 (ППК)&quot;,
        ///    &quot;cityId&quot;: 110
        ///  },
        ///  {
        ///    &quot;id&quot;: 145007,
        ///    &quot;title&quot;: &quot;Профессионально-техническое училище №1&quot;,
        ///    &quot;cityId&quot;: 110
        ///  },
        ///  {
        ///    &quot;id&quot;: 142505,
        ///    &quot;title&quot;: &quot;Детско-юношеская спортивная школа олимпийского резерва №1&quot;,
        ///    &quot;cityId&quot;: 110
        ///  },
        ///  {
        ///    &quot;id&quot;: 104770,
        ///    &quot;title&quot;: &quot;Музыкальная школа №1&quot;,
        ///    &quot;cityId&quot;: 110
        ///  },
        ///  {
        ///    &quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsPermJson {
            get {
                return ResourceManager.GetString("SchoolsPermJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:577,&quot;title&quot;:&quot;Школа № 644&quot;,&quot;cityId&quot;:2},{&quot;id&quot;:1612,&quot;title&quot;:&quot;Школа № 645 (до 2005 г.)&quot;,&quot;cityId&quot;:2},{&quot;id&quot;:382,&quot;title&quot;:&quot;Школа № 645 (бывш. № 33)&quot;,&quot;cityId&quot;:2},{&quot;id&quot;:112352,&quot;title&quot;:&quot;Начальная школа – детский сад № 646&quot;,&quot;cityId&quot;:2},{&quot;id&quot;:5176,&quot;title&quot;:&quot;Школа № 647 «Тайми»&quot;,&quot;cityId&quot;:2},{&quot;id&quot;:9090,&quot;title&quot;:&quot;Гимназия № 649&quot;,&quot;cityId&quot;:2},{&quot;id&quot;:34,&quot;title&quot;:&quot;Гимназия № 652&quot;,&quot;cityId&quot;:2},{&quot;id&quot;:58452,&quot;title&quot;:&quot;Школа-интернат № 652&quot;,&quot;cityId&quot;:2},{&quot;id&quot;:265,&quot;title&quot;:&quot;Школа № 653&quot;,&quot;cityId&quot;:2},{&quot;id&quot;:1320,&quot;title&quot;:&quot;Школа № 654 «Хо [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsPetersburgJson {
            get {
                return ResourceManager.GetString("SchoolsPetersburgJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 53101,
        ///    &quot;title&quot;: &quot;Школа №1&quot;,
        ///    &quot;cityId&quot;: 119
        ///  },
        ///  {
        ///    &quot;id&quot;: 327015,
        ///    &quot;title&quot;: &quot;Колледж металлообработки и автосервиса (РКМиА, бывш. Профессиональный лицей №1)&quot;,
        ///    &quot;cityId&quot;: 119
        ///  },
        ///  {
        ///    &quot;id&quot;: 266657,
        ///    &quot;title&quot;: &quot;Гимназия №1&quot;,
        ///    &quot;cityId&quot;: 119
        ///  },
        ///  {
        ///    &quot;id&quot;: 119810,
        ///    &quot;title&quot;: &quot;Лицей №1 при РГУ&quot;,
        ///    &quot;cityId&quot;: 119
        ///  },
        ///  {
        ///    &quot;id&quot;: 133031,
        ///    &quot;title&quot;: &quot;Музыкальная школа №1&quot;,
        ///    &quot;cityId&quot;: 119
        ///  },
        ///  {
        ///    &quot;id&quot;: 988229,
        ///    &quot;title&quot;: &quot;Дет [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsRostovJson {
            get {
                return ResourceManager.GetString("SchoolsRostovJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 202801,
        ///    &quot;title&quot;: &quot;Школа №1&quot;,
        ///    &quot;cityId&quot;: 123
        ///  },
        ///  {
        ///    &quot;id&quot;: 312032,
        ///    &quot;title&quot;: &quot;Гимназия №1&quot;,
        ///    &quot;cityId&quot;: 123
        ///  },
        ///  {
        ///    &quot;id&quot;: 111617,
        ///    &quot;title&quot;: &quot;Лицей №1&quot;,
        ///    &quot;cityId&quot;: 123
        ///  },
        ///  {
        ///    &quot;id&quot;: 131748,
        ///    &quot;title&quot;: &quot;Экспериментальная музыкально-хоровая школа-десятилетка (ЭМХШД №1)&quot;,
        ///    &quot;cityId&quot;: 123
        ///  },
        ///  {
        ///    &quot;id&quot;: 75641,
        ///    &quot;title&quot;: &quot;Музыкальная школа №1 им. Шостаковича&quot;,
        ///    &quot;cityId&quot;: 123
        ///  },
        ///  {
        ///    &quot;id&quot;: 315953,
        ///    &quot;title&quot;: &quot;Детско-юн [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsSamaraJson {
            get {
                return ResourceManager.GetString("SchoolsSamaraJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 202150,
        ///    &quot;title&quot;: &quot;Школа № 1&quot;,
        ///    &quot;cityId&quot;: 151
        ///  },
        ///  {
        ///    &quot;id&quot;: 9911,
        ///    &quot;title&quot;: &quot;Башкирская республиканская гимназия-интернат (БРГИ) 1 им. Р. Гарипова&quot;,
        ///    &quot;cityId&quot;: 151
        ///  },
        ///  {
        ///    &quot;id&quot;: 7768,
        ///    &quot;title&quot;: &quot;Гимназия № 1&quot;,
        ///    &quot;cityId&quot;: 151
        ///  },
        ///  {
        ///    &quot;id&quot;: 54515,
        ///    &quot;title&quot;: &quot;Лицей № 1&quot;,
        ///    &quot;cityId&quot;: 151
        ///  },
        ///  {
        ///    &quot;id&quot;: 2488,
        ///    &quot;title&quot;: &quot;Музыкальная школа № 1&quot;,
        ///    &quot;cityId&quot;: 151
        ///  },
        ///  {
        ///    &quot;id&quot;: 224230,
        ///    &quot;title&quot;: &quot;Детско-юношеская спорти [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsUfaJson {
            get {
                return ResourceManager.GetString("SchoolsUfaJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 71720,
        ///    &quot;title&quot;: &quot;Школа №1&quot;,
        ///    &quot;cityId&quot;: 37
        ///  },
        ///  {
        ///    &quot;id&quot;: 225800,
        ///    &quot;title&quot;: &quot;Школа «Полюс №1»&quot;,
        ///    &quot;cityId&quot;: 37
        ///  },
        ///  {
        ///    &quot;id&quot;: 120188,
        ///    &quot;title&quot;: &quot;Гимназия №1&quot;,
        ///    &quot;cityId&quot;: 37
        ///  },
        ///  {
        ///    &quot;id&quot;: 65371,
        ///    &quot;title&quot;: &quot;Гимназия при ВПК №1&quot;,
        ///    &quot;cityId&quot;: 37
        ///  },
        ///  {
        ///    &quot;id&quot;: 281441,
        ///    &quot;title&quot;: &quot;Школа-интернат №1&quot;,
        ///    &quot;cityId&quot;: 37
        ///  },
        ///  {
        ///    &quot;id&quot;: 175672,
        ///    &quot;title&quot;: &quot;Вечерняя школа №1&quot;,
        ///    &quot;cityId&quot;: 37
        ///  },
        ///  {
        ///    &quot;id&quot;: 62331,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsVladivostokJson {
            get {
                return ResourceManager.GetString("SchoolsVladivostokJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 53649,
        ///    &quot;title&quot;: &quot;Школа № 1&quot;,
        ///    &quot;cityId&quot;: 10
        ///  },
        ///  {
        ///    &quot;id&quot;: 742815,
        ///    &quot;title&quot;: &quot;Царицынская школа № 1&quot;,
        ///    &quot;cityId&quot;: 10
        ///  },
        ///  {
        ///    &quot;id&quot;: 110080,
        ///    &quot;title&quot;: &quot;Школа «Гармония-1»&quot;,
        ///    &quot;cityId&quot;: 10
        ///  },
        ///  {
        ///    &quot;id&quot;: 295408,
        ///    &quot;title&quot;: &quot;Гимназия № 1&quot;,
        ///    &quot;cityId&quot;: 10
        ///  },
        ///  {
        ///    &quot;id&quot;: 55159,
        ///    &quot;title&quot;: &quot;Лицей № 1&quot;,
        ///    &quot;cityId&quot;: 10
        ///  },
        ///  {
        ///    &quot;id&quot;: 169137,
        ///    &quot;title&quot;: &quot;Школа-интернат № 1&quot;,
        ///    &quot;cityId&quot;: 10
        ///  },
        ///  {
        ///    &quot;id&quot;: 250713,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsVolgogradJson {
            get {
                return ResourceManager.GetString("SchoolsVolgogradJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 94982,
        ///    &quot;title&quot;: &quot;Школа № 1&quot;,
        ///    &quot;cityId&quot;: 42
        ///  },
        ///  {
        ///    &quot;id&quot;: 80399,
        ///    &quot;title&quot;: &quot;Школа искусств № 1&quot;,
        ///    &quot;cityId&quot;: 42
        ///  },
        ///  {
        ///    &quot;id&quot;: 78101,
        ///    &quot;title&quot;: &quot;Музыкальная школа № 1 при ВГАИ&quot;,
        ///    &quot;cityId&quot;: 42
        ///  },
        ///  {
        ///    &quot;id&quot;: 49863,
        ///    &quot;title&quot;: &quot;Художественная школа № 1&quot;,
        ///    &quot;cityId&quot;: 42
        ///  },
        ///  {
        ///    &quot;id&quot;: 188512,
        ///    &quot;title&quot;: &quot;Колледж № 1&quot;,
        ///    &quot;cityId&quot;: 42
        ///  },
        ///  {
        ///    &quot;id&quot;: 199853,
        ///    &quot;title&quot;: &quot;Учебно-воспитательный комплекс № 1&quot;,
        ///    &quot;cityId&quot;: 4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchoolsVoronezJson {
            get {
                return ResourceManager.GetString("SchoolsVoronezJson", resourceCulture);
            }
        }
    }
}
